project_id = "xwqmdhnuthprzfbyoxlb"

[functions.delete-user]
verify_jwt = false

[functions.upload-to-archive]
verify_jwt = false

[functions.check-flashcard-reviews]
verify_jwt = false

[functions.check-media-ocr-status]
verify_jwt = false

[functions.process-ocr]
verify_jwt = false

[functions.fetch-media]
verify_jwt = false

[functions.extract-metadata]
verify_jwt = false
