project_id = "xwqmdhnuthprzfbyoxlb"

[functions.delete-user]
verify_jwt = false

[functions.upload-to-archive]
verify_jwt = false

[functions.check-flashcard-reviews]
verify_jwt = false

[functions.process-pdf-ocr]
verify_jwt = false

[functions.check-pdf-ocr-status]
verify_jwt = false
